name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev
      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("remotes", "devtools"))'
      - name: Install package dependencies
        run: Rscript -e 'remotes::install_deps(dependencies = TRUE)'
      - name: Run R CMD check
        run: Rscript -e 'devtools::check(error_on = "warning")'
